"""empty message

Revision ID: 7e1f2a71a729
Revises:
Create Date: 2022-10-04 16:53:11.723928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1f2a71a729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE todos SET completed = False WHERE completed is NULL")
    op.alter_column("todos", "completed", nullable = False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
